[package]
name = "bin"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.18", features = ["default", "derive", "env"] }
ethereum-types = "0.14.1"
circuits = { path = "../circuits" }
gadgets = { path = "../gadgets" }
